name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0
      - name: Setup Xvfb and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth
      - name: Trigger SedStart test run
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.API_SEDSTART}}
          project_id: 18
          test_id: 74
          profile_id: 36
          browser: chrome
          headless: false
          
