name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0
      - name: Setup Xvfb and dependencies
        run: |
          apt-get update && apt-get install -y \
          curl \
          ca-certificates \
          xvfb \
          xauth \
          libnss3 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libx11-xcb1 \
          libdrm2 \
          libgbm1 \
          libasound2 \
          libxshmfence1 \
          libxrandr2 \
          libxcomposite1 \
          libxcursor1 \
          libxi6 \
          libxtst6 \
          fonts-liberation \
          --no-install-recommends && \
          rm -rf /var/lib/apt/lists/*

      - name: Trigger SedStart test run
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.API_SEDSTART}}
          project_id: 18
          test_id: 74
          profile_id: 36
          browser: chrome
          headless: false
          
