name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 18
          test_id: 74
          profile_id: 36
          browser: chrome
          headless: false
