name: Sedstart Local Macos

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright
        run: npm install -g playwright@1.52.0

      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.API_SEDSTART }}
          project_id: 459
          test_id: 2136
          profile_id: 945
          headless: false
          browser: chrome 
          environment: QA
